import Head from "next/head";
import Image from "next/image";
export default function Home() {
  return (
    <>
      <Head>
        <title>ChromaFX</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        ChromaFX
        <Image alt="test" src={"/finance.svg"} width={580} height={580} />
      </main>
    </>
  );
}
