import Head from "next/head";
import { useState } from "react";
import EmailModal from "~/components/Index/EmailModal";
import Header from "~/components/Index/Header";
export default function Home() {
  const [isEmailModalOpen, setIsEmailModalOpen] = useState(false);
  return (
    <>
      <Head>
        <title>ChromaFX</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <main
          onClick={(e) => {
            const element = e.target as HTMLElement;
            if (element.tagName.toLowerCase() === "button") return;
            setIsEmailModalOpen(false);
          }}
          className={`flex min-h-screen flex-col ${
            isEmailModalOpen ? `opacity-30` : ``
          }`}
        >
          <Header setIsEmailModalOpen={setIsEmailModalOpen} />
        </main>
        <EmailModal
          setIsEmailModalOpen={setIsEmailModalOpen}
          isEmailModalOpen={isEmailModalOpen}
        />
      </>
    </>
  );
}
