import Head from "next/head";
import Header from "~/components/Index/Header";
export default function Home() {
  return (
    <>
      <Head>
        <title>ChromaFX</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col ">
        <Header />
      </main>
    </>
  );
}
